### ISSUE TITLE
Wrong decription

### ISSUE THREAD

**Issue by andreyurch** [svm-zhang/AGOUTI#12]
Hello,
It seems that command in the examples 
bwa mem -M example.fasta example.1.fq example.2.fq | samtools view - > example.bam

produces a SAM file instead of a BAM.  To receive a BAM we need to use

bwa mem -M example.fasta example.1.fq example.2.fq | samtools view -Sb - > example.bam

**Comment by svm-zhang** [comment]
Hello @andreyurch,

You are absolutely correct. Thanks very much for pointing it out! I will update the README. :)

Simo

**Comment by svm-zhang** [comment]
Hello @andreyurch,

Samtools command line is now fixed :) Thanks!

Simo
