### ISSUE TITLE
KeyError when scaffold ID contains additional '_'

### ISSUE THREAD

**Issue by andreyurch** [svm-zhang/AGOUTI#13]
Hello, the genome size is 1.5Gb

017-06-08 13:28:43,230 - INFO - AGOUTI_DENOISE PROGRESS - Succeeded
2017-06-08 13:28:43,238 - INFO - AGOUTI_DENOISE PROGRESS - Denoise took in 27.59 min CPU time
2017-06-08 13:28:43,245 - INFO - AGOUTI_DENOISE PROGRESS - 1187 contig pairs filtered for spanning across >1 gene models
2017-06-08 13:28:43,252 - INFO - AGOUTI_DENOISE PROGRESS - 12753 contig pairs filtered for not being one of the four combinations
2017-06-08 13:28:43,259 - INFO - AGOUTI_DENOISE PROGRESS - 914076 contig pairs filtered for less support
2017-06-08 13:28:43,266 - INFO - AGOUTI_DENOISE PROGRESS - 42445 contig pairs for scaffolding
2017-06-08 13:28:43,309 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Building graph from joining reads pairs
2017-06-08 13:28:43,964 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Build graph took 0.0110 min CPU time
2017-06-08 13:28:43,972 - INFO - AGOUTI_SCAFFOLDING PROGRESS - 52302 vertices in the graph
2017-06-08 13:28:43,973 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Simplifying graph
2017-06-08 13:28:44,415 - INFO - AGOUTI_SCAFFOLDING PROGRESS - 5713 Edges removed due to insufficient supports
2017-06-08 13:28:44,416 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Start graph walk
2017-06-08 13:31:41,845 - INFO - AGOUTI_SCAFFOLDING PROGRESS - number of visited nodes: 52302
2017-06-08 13:31:41,845 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Scaffolding took 2.9553 min CPU time
2017-06-08 13:31:43,680 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Graph Reconciliation
2017-06-08 13:31:45,271 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Reconciliation took 0.0267 min CPU time
2017-06-08 13:31:45,313 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Report scaffolding paths
2017-06-08 13:31:45,435 - INFO - AGOUTI_SCAFFOLDING PROGRESS - Visualize graph in DOT
2017-06-08 13:31:46,044 - INFO - AGOUTI_PATH PROGRESS - Analyzing scaffolding paths
2017-06-08 13:31:46,046 - INFO - AGOUTI_PATH PROGRESS - [BEGIN] Reading file with shred info
2017-06-08 13:32:10,048 - INFO - AGOUTI_PATH PROGRESS - Number of shredded contigs parsed: 1614721
2017-06-08 13:32:10,048 - INFO - AGOUTI_PATH PROGRESS - [DONE]
Traceback (most recent call last):
  File "/export/home/aay2c/app2/AGOUTI/agouti.py", line 288, in <module>
    main()
  File "/export/home/aay2c/app2/AGOUTI/agouti.py", line 285, in main
    args.func(args)
  File "/export/home/aay2c/app2/AGOUTI/agouti.py", line 222, in run_scaffolder
    prefix)
  File "/export/home/aay2c/app2/AGOUTI/src/agouti_path.py", line 39, in agouti_path_main
    report_consistency(agoutiPaths, dOriPaths, vertex2Name, outDir, prefix)
  File "/export/home/aay2c/app2/AGOUTI/src/agouti_path.py", line 132, in report_consistency
    if stop > len(dOriPaths[curOrigScaf]):
KeyError: 'opera_scaffold'

**Comment by svm-zhang** [comment]
Hello @andreyurch,

I see you shredded the assembly first and run AGOUTI on the shredded contigs, right?

Could you please provide me with the following info:

1. the shred and scaffold command lines you used;
2. Snapshots of your shred info file;
3. Some header lines from your shred contig fasta file;
4. Some header lines from your original fasta file.

Simo

**Comment by andreyurch** [comment]
Hello Simo,
Yes, I used a shredded assembly.
1. python ~/app2/AGOUTI/agouti.py shred -assembly assembly.fasta -p assembly -mlg 25
python ~/app2/AGOUTI/agouti.py scaffold -assembly assembly.ctg.fasta -bam assembly.ctg.bam -gff assembly.ctg.gff -outdir ./assembly -shredpath assembly.shred.info.txt -minMQ 50 -maxFracMM 0.02
2.Snapshots
>opera_scaffold_1
opera_scaffold_1_0      opera_scaffold_1_1      32
opera_scaffold_1_1      opera_scaffold_1_2      227
opera_scaffold_1_2      opera_scaffold_1_3      24
opera_scaffold_1_3      opera_scaffold_1_4      71
opera_scaffold_1_4      opera_scaffold_1_5      60
opera_scaffold_1_5      opera_scaffold_1_6      39
opera_scaffold_1_6      opera_scaffold_1_7      131
opera_scaffold_1_7      opera_scaffold_1_8      94
opera_scaffold_1_8      opera_scaffold_1_9      2471
opera_scaffold_1_9      opera_scaffold_1_10     554

>opera_scaffold_1362329
opera_scaffold_1362329	NA	NA
>opera_scaffold_1362330
opera_scaffold_1362330	NA	NA
>opera_scaffold_1362331
opera_scaffold_1362331	NA	NA
>opera_scaffold_1362332
opera_scaffold_1362332	NA	NA
>opera_scaffold_1362333
opera_scaffold_1362333	NA	NA

3. Headers
>opera_scaffold_2_5748
>opera_scaffold_2_5749
>opera_scaffold_2_5750
>opera_scaffold_2_5751
>opera_scaffold_2_5752
>opera_scaffold_2_5753
>opera_scaffold_2_5754
>opera_scaffold_2_5755
>opera_scaffold_2_5756
>opera_scaffold_2_5757
>opera_scaffold_2_5758
>opera_scaffold_2_5759
>opera_scaffold_2_5760
>opera_scaffold_2_5761
>opera_scaffold_2_5762
>opera_scaffold_2_5763
>opera_scaffold_2_5764
>opera_scaffold_2_5765
>opera_scaffold_2_5766
>opera_scaffold_2_5767
>opera_scaffold_2_5768
>opera_scaffold_2_5769

4.Headers original
>opera_scaffold_1	length: 39042984	cov: 33.3
>opera_scaffold_2	length: 35329905	cov: 32.7
>opera_scaffold_3	length: 32566605	cov: 32.7
>opera_scaffold_4	length: 29818004	cov: 32.8
>opera_scaffold_5	length: 28278219	cov: 31.2
>opera_scaffold_6	length: 28082432	cov: 33.1
>opera_scaffold_7	length: 26535665	cov: 32.9
>opera_scaffold_8	length: 25980233	cov: 31.8
>opera_scaffold_9	length: 24550709	cov: 34.6
>opera_scaffold_10	length: 23801180	cov: 33.4
>opera_scaffold_11	length: 23352918	cov: 32.7
>opera_scaffold_12	length: 22702101	cov: 35.6
>opera_scaffold_13	length: 22678191	cov: 32.6
>opera_scaffold_14	length: 22087482	cov: 31.8

**Comment by svm-zhang** [comment]
Hello @andreyurch,

Thanks for these info. My guess now is that I probably messed up in parsing the seq id. Let me check. I will get back to you.

Simo

**Comment by andreyurch** [comment]
Thank you!  Does it make sense for me to change my scaffold Ids?

**Comment by svm-zhang** [comment]
Not sure yet... I will try to look at it tonight

**Comment by svm-zhang** [comment]
I think it is caused by the scaffold seq ID. Specifically in your case, the underscore in between "opera" and "scaffold" for ID "opera_scaffold_1". Let me work on a patch for this and get back to you.

But at the same time, I think you can update your scaffold ID, such as "operascaffold_1", and AGOUTI should not bark (hopefully) :)

Simo

**Comment by andreyurch** [comment]
I have checked using just two genomic scaffolds different variants of the headers including the original one opera_scaffold_.  They all worked and finished successfully :).

**Comment by svm-zhang** [comment]
Hello @andreyurch,

It worked for you when you updated your ID?

Sorry for the delay, but my local cluster have been experiencing I/O problem that greatly slows down my debugging :) Anyway.... I just pushed a quick-and-dirty patch, and I think it should now work for you.

Please do let me know.

Simo

**Comment by andreyurch** [comment]
Hello Simo,

Yes, it works well now after the patching. Thank you very much!   
The only question : If I use the shredded mode I receive N50 = 75kb, while the original assembly is around N50=12.5 MB with 92% complete BUSCO (tetrapoda) genes...   Is it expected behaviour??

**Comment by svm-zhang** [comment]
Hello @andreyurch,

Great to hear that and thanks for letting me know.

I'd say it is likely that you will end up with a worse assembly by using the shredded mode. May I ask how was the result without shredding, i.e. directly using AGOUTI on your original scaffolds? 

Simo

**Comment by andreyurch** [comment]
Without the shredding It improved the assembly from N50=12.5 to N50=13.7 Mb

**Comment by svm-zhang** [comment]
AGOUTI shreds original scaffolds and tries to patch them up based on RNA evidences. For those shredded contigs that are not scaffolded by AGOUTI, AGOUTI tries to recover the original scaffolding paths (that's where your error was about), such that one does not lose too much contiguity. 

It is possible that one end up with a worse assembly. For instance, scaffold A and B shredded into three pieces: A1, A2, A3, and B1, B2, B3. If RNA-seq suggests A2 connecting to B2, then the final assembly will be A1, A2-N-B2, A3, B3. The N50 calculated from this new sets of sequences is likely to be worse than the original A1-N-A2-N-A3, and B1-N-B2-N-B3 (it can be also better, but with my experiments so far it is less likely). My point here is that if you have lots of such cases, i.e. inconsistencies between DNA-based scaffolds and ones based on RNA evidences, then it is likely AGOUTI will give worse assembly.

Could you please check how many inconsistencies?

Of course, these all can be some bugs in my original scaffolds recovering codes. I might need to write some codes to generate some debugging messages to help you in this case :)

Simo

**Comment by andreyurch** [comment]
Ok, I will check the files and let you know. At the same time, I am thinking about the role of transposons here. Many of them can be expressed and much important can contain the ORFs which will be identified by AUGUSTUS. That is why it strongly recommended to mask all the repeats before the annotation using AUGUSTUS or similar tools.

**Comment by svm-zhang** [comment]
Did you mean that transposons create ambiguous reads mapping which is not used by AGOUTI, and that's why many connections failed to be picked up? If so, how masking all repeats before annotation would help our results here? I might miss something here, could you be more specific?

Another thing you could try is to lower your minMQ and -k=2, and/or increase maxFracMM to see if you could get better result.

Simo

**Comment by andreyurch** [comment]
I mean that some transposons can be expressed and identified using Augustus as genes. Then, AGOUTI can use them as gene models and find false links based on the transposon regions because of the repetitive nature of transposons..  It just a guess...  If it is the case we expect to see circular subgraphs in AGOUTI

**Comment by svm-zhang** [comment]
But the reads mapped to those regions are likely ambiguous ones, no? AGOUTI won't use these read pairs such that these false links can be avoided.

**Comment by andreyurch** [comment]
I am not sure here. The transposons are very tricky because they have a broad range of nucleotide differences among them being repeats at the same time.  Some of them can produce quite good alignments (above 30 for bwa mem). I plan to explore this question for my genome after the gaplclosing and repeat identification.

**Comment by svm-zhang** [comment]
Interesting :) What level of variation we are looking at? Do you know some papers that can recommend on this matter?

And could you please open another ticket on this transposon matter? If I get time, I will try to look into my data and see what happens. But please keep me posted on this.

Simo
