### ISSUE TITLE
845 - ERROR - AGOUTI_GFF PROGRESS - Found zero genes

### ISSUE THREAD

**Issue by mars1198** [svm-zhang/AGOUTI#18]
I tried to use AGOUTI with a simole command 

python2 agouti.py scaffold -assembly ./nc/assembly_not_changed.fasta -bam ./nc/d9_S1_L001_R1_001.bam -gff ./nc/not changed.gff -outdir ./output

But i always become these two ERRORS
845 - ERROR - AGOUTI_GFF PROGRESS - Found zero genes
845 - ERROR - AGOUTI_GFF PROGRESS - Please check your GFF file

AGOUTI version us v0.2.5

I have checked the GFF file and it seems to be ok. Is that  a new bug?

**Comment by svm-zhang** [comment]
Hello @mars1198,

Sorry for the very late reply. I did not get any notification email from github for some reason.

Could you please share with me the first 100 genes in your GFF if possible? I can take a look and figure out why?

**Comment by svm-zhang** [comment]
Close now. Please feel free to reopen.
