### ISSUE TITLE
'gap' feature request

### ISSUE THREAD

**Issue by TakashiKoyama** [svm-zhang/AGOUTI#3]
Hi Simo,

I want to know which 'N's AGOUTI added after the scaffolding.
Could you consider adding 'gap' features in the revised gff?

Takashi

**Comment by svm-zhang** [comment]
Hi Takashi,

So you'd like to know coordinates of gaps in the GFF, like the following?

scaf_1 AGOUTI gap 1000 2000 . . . ID=...;

Do I understand you here right?

Simo

**Comment by TakashiKoyama** [comment]
Hi Simo,

Yes. Is it possible?

Takashi

**Comment by svm-zhang** [comment]
Hi Takashi,

It's possible. Please give me some time for this. I have a deadline at hand and it might take a bit longer. I will let you know.

Simo

**Comment by TakashiKoyama** [comment]
Hi Simo,

OK. Thank your for your kind helps!

Takashi

**Comment by svm-zhang** [comment]
Hi Takashi,

I just made a new patch. Could you give a try? Now in the GFF, you will have `scaffold` and `gap` features, like:

scaf_1 AGOUTI scaffold 1 10000 . . . ID=scaf_1
scaf_1 AGOUTI gap 2000 3000 . . . Parent=scaf_1
... gene models on scaf_1 ...

Note that the positions are 1-based. Hope this helps!

Please let me know if this works for you.

Simo

**Comment by TakashiKoyama** [comment]
Hi Simo,

Everything works great! Thank you for your quick work!

Takashi

**Comment by svm-zhang** [comment]
No problem Takashi! Glad to help!

I am gonna close this thread now.
